
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Mar 11 22:02:47 CET 2021
//----------------------------------------------------

package pum.analyze;

/** CUP generated class containing symbol constants. */
public class LexicalTokens {
  /* terminals */
  public static final int CSTI = 4;
  public static final int error = 1;
  public static final int IDF = 3;
  public static final int SEMI = 2;
  public static final int EOF = 0;
}

