
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Mar 13 16:03:04 CET 2021
//----------------------------------------------------

package pum.analyze;

/** CUP generated class containing symbol constants. */
public class LexicalCodes {
  /* terminals */
  public static final int TIMES = 10;
  public static final int CSTSTR = 19;
  public static final int IDF = 16;
  public static final int ACCRIGHT = 4;
  public static final int PLUS = 8;
  public static final int INT = 5;
  public static final int EQUAL = 7;
  public static final int SEMI = 2;
  public static final int PRINTL = 15;
  public static final int CSTFLOAT = 18;
  public static final int CSTINT = 17;
  public static final int FLOAT = 6;
  public static final int EOF = 0;
  public static final int DIVIDE = 11;
  public static final int PARRIGHT = 13;
  public static final int MINUS = 9;
  public static final int PRINT = 14;
  public static final int error = 1;
  public static final int ACCLEFT = 3;
  public static final int PARLEFT = 12;
}

